import { useState } from "react";
import { apiGenerateResolution, apiSubmitResolutionFeedback } from "../api/client";
import type { Finding, Resolution, ResolutionStep } from "../types";
import ExecutionSessionPanel from "./ExecutionSession";

interface FindingResolutionProps {
  finding: Finding;
}

function ConfidenceBadge({ confidence }: { confidence: Resolution["confidence"] }) {
  const colors = {
    low: "var(--warn)",
    medium: "var(--info)",
    high: "var(--good)",
  };
  return (
    <span className="badge" style={{ background: colors[confidence] }}>
      {confidence} confidence
    </span>
  );
}

function StepCard({ step }: { step: ResolutionStep }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (step.command) {
      navigator.clipboard.writeText(step.command);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div
      className="card"
      style={{
        padding: 12,
        marginTop: 12,
        background: step.requires_confirmation ? "var(--bg-warn)" : undefined,
      }}
    >
      <div style={{ display: "flex", alignItems: "start", gap: 12 }}>
        <div
          style={{
            background: step.is_safe ? "var(--good)" : "var(--bad)",
            color: "white",
            width: 24,
            height: 24,
            borderRadius: "50%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontWeight: 700,
            fontSize: 14,
            flexShrink: 0,
          }}
        >
          {step.order}
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 700 }}>{step.description}</div>
          {step.command ? (
            <div style={{ marginTop: 8 }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <code
                  style={{
                    display: "block",
                    background: "var(--bg-secondary)",
                    padding: "8px 12px",
                    borderRadius: 4,
                    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas",
                    fontSize: 13,
                    flex: 1,
                    overflowX: "auto",
                  }}
                >
                  {step.command}
                </code>
                <button
                  className="btn secondary"
                  onClick={handleCopy}
                  style={{ marginLeft: 8, fontSize: 12, padding: "4px 8px" }}
                >
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
              {step.expected_output ? (
                <div className="muted" style={{ marginTop: 4, fontSize: 12 }}>
                  Expected: <code>{step.expected_output}</code>
                </div>
              ) : null}
            </div>
          ) : null}
          {step.requires_confirmation ? (
            <div className="badge high" style={{ marginTop: 8, fontSize: 12 }}>
              ⚠️ Requires confirmation
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
}

function ResolutionModal({
  resolution,
  findingTitle,
  onClose,
  onFeedback,
  onRunWithAgent,
}: {
  resolution: Resolution;
  findingTitle: string;
  onClose: () => void;
  onFeedback: (feedback: "helpful" | "not_helpful" | "partially_helpful") => void;
  onRunWithAgent: () => void;
}) {
  return (
    <div
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "rgba(0, 0, 0, 0.6)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
        padding: 20,
      }}
      onClick={onClose}
    >
      <div
        className="card"
        style={{
          maxWidth: 800,
          width: "100%",
          maxHeight: "90vh",
          overflow: "auto",
          padding: 24,
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "start" }}>
          <div>
            <h2 style={{ margin: 0 }}>AI-Powered Resolution</h2>
            <div className="muted" style={{ marginTop: 6 }}>
              Generated by {resolution.model_used}
            </div>
          </div>
          <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
            <ConfidenceBadge confidence={resolution.confidence} />
            <button className="btn secondary" onClick={onClose} style={{ fontSize: 20, padding: "4px 12px" }}>
              ×
            </button>
          </div>
        </div>

        {/* Analysis */}
        <div style={{ marginTop: 20 }}>
          <div style={{ fontWeight: 700, marginBottom: 8 }}>Root Cause Analysis</div>
          <div className="muted">{resolution.analysis}</div>
        </div>

        {/* Safety Warnings */}
        {resolution.safety_notes.length > 0 ? (
          <div className="card" style={{ marginTop: 20, background: "var(--bg-warn)", padding: 12 }}>
            <div style={{ fontWeight: 700, marginBottom: 8 }}>⚠️ Safety Notes</div>
            <ul style={{ margin: 0, paddingLeft: 20 }}>
              {resolution.safety_notes.map((note, i) => (
                <li key={i} className="muted">
                  {note}
                </li>
              ))}
            </ul>
          </div>
        ) : null}

        {/* Steps */}
        <div style={{ marginTop: 20 }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 8 }}>
            <div style={{ fontWeight: 700 }}>Remediation Steps</div>
            {resolution.steps.some((s) => s.command) && (
              <button
                className="btn"
                onClick={onRunWithAgent}
                style={{ fontSize: 12, padding: "4px 12px" }}
              >
                ▶ Run with Agent
              </button>
            )}
          </div>
          {resolution.steps.map((step) => (
            <StepCard key={step.order} step={step} />
          ))}
        </div>

        {/* Verification */}
        {resolution.verification ? (
          <div className="card" style={{ marginTop: 20, background: "var(--bg-good)", padding: 12 }}>
            <div style={{ fontWeight: 700, marginBottom: 8 }}>✓ Verification</div>
            <div className="muted" style={{ marginBottom: 8 }}>
              After applying the fix, run this command to verify:
            </div>
            <code
              style={{
                display: "block",
                background: "var(--bg-secondary)",
                padding: "8px 12px",
                borderRadius: 4,
                fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas",
                fontSize: 13,
              }}
            >
              {resolution.verification.command}
            </code>
            <div className="muted" style={{ marginTop: 4, fontSize: 12 }}>
              Expected: <code>{resolution.verification.expected_output}</code>
            </div>
          </div>
        ) : null}

        {/* References */}
        {resolution.references.length > 0 ? (
          <div style={{ marginTop: 20 }}>
            <div style={{ fontWeight: 700, marginBottom: 8 }}>References</div>
            <ul style={{ margin: 0, paddingLeft: 20 }}>
              {resolution.references.map((ref, i) => (
                <li key={i} className="muted">
                  <a href={ref} target="_blank" rel="noopener noreferrer">
                    {ref}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        ) : null}

        {/* Feedback */}
        <div style={{ marginTop: 24, paddingTop: 20, borderTop: "1px solid var(--border)" }}>
          <div style={{ fontWeight: 700, marginBottom: 12 }}>Was this resolution helpful?</div>
          <div style={{ display: "flex", gap: 8 }}>
            <button className="btn secondary" onClick={() => onFeedback("helpful")}>
              👍 Helpful
            </button>
            <button className="btn secondary" onClick={() => onFeedback("partially_helpful")}>
              🤷 Partially
            </button>
            <button className="btn secondary" onClick={() => onFeedback("not_helpful")}>
              👎 Not helpful
            </button>
          </div>
        </div>

        {/* Metadata */}
        <div className="muted" style={{ marginTop: 20, fontSize: 12 }}>
          Generated at {new Date(resolution.generated_at).toLocaleString()}
          {resolution.tokens_used ? ` · ${resolution.tokens_used} tokens` : ""}
          {resolution.latency_ms ? ` · ${(resolution.latency_ms / 1000).toFixed(1)}s` : ""}
        </div>
      </div>
    </div>
  );
}

export default function FindingResolution({ finding }: FindingResolutionProps) {
  const [resolution, setResolution] = useState<Resolution | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showExecution, setShowExecution] = useState(false);

  const handleGetFix = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await apiGenerateResolution(finding.id);
      setResolution(res);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      if (e instanceof Error && e.message.includes("503")) {
        setError("AI resolution service not configured. Set ANTHROPIC_API_KEY to enable this feature.");
      }
    } finally {
      setLoading(false);
    }
  };

  const handleFeedback = async (feedback: "helpful" | "not_helpful" | "partially_helpful") => {
    if (!resolution) return;
    try {
      await apiSubmitResolutionFeedback(resolution.resolution_id, { feedback });
      alert("Thank you for your feedback!");
    } catch (e) {
      console.error("Failed to submit feedback:", e);
    }
  };

  return (
    <>
      <div style={{ marginTop: 8 }}>
        <button className="btn secondary" onClick={handleGetFix} disabled={loading} style={{ fontSize: 13 }}>
          {loading ? "Generating..." : "🤖 Get AI Fix"}
        </button>
        {error ? (
          <div className="badge high" style={{ marginTop: 8, fontSize: 12 }}>
            {error}
          </div>
        ) : null}
      </div>

      {resolution && !showExecution ? (
        <ResolutionModal
          resolution={resolution}
          findingTitle={finding.title}
          onClose={() => setResolution(null)}
          onFeedback={handleFeedback}
          onRunWithAgent={() => setShowExecution(true)}
        />
      ) : null}

      {resolution && showExecution ? (
        <ExecutionSessionPanel
          resolution={resolution}
          findingTitle={finding.title}
          onClose={() => {
            setShowExecution(false);
            setResolution(null);
          }}
        />
      ) : null}
    </>
  );
}
